# -*- coding: utf-8 -*-
"""DAY-3 PYTHON AND MACHINE LEARNING.PY

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ovNH89GnAKVdWsoZNRrDhrWPaHbG4wN8
"""

from google.colab import files
uploaded = files.upload()

# ==========================================================
# STEP 1 - IMPORT LIBRARIES
# ==========================================================
import pandas as pd
import numpy as np

# ==========================================================
# STEP 2 - LOAD DATASET
# ==========================================================

df = pd.read_csv("Titanic-Dataset.csv")

print("FIRST FIVE RECORDS")
print(df.head())

print(df.info())

print(df.shape)

print(df.columns)

print(df.describe)

print(df.isnull().sum())

print(df.duplicated().sum())

print(df["Cabin"].unique())

print(df.tail())

print(df["Cabin"].value_counts())

print(df.dtypes)

y = df["Cabin"]
print(y.head())

print(df["Sex"].value_counts())

df["Age"].fillna(df["Age"].mean(),inplace=True)

print(df.isnull().sum())

df["Embarked"].fillna(df["Embarked"].mode()[0],inplace=True)

print(df.isnull().sum())

df["Cabin"].fillna(df["Cabin"].mode()[0],inplace=True)

print(df.isnull().sum())

df.drop("SibSp", axis=1, inplace=True)

print(df.isnull().sum())

